### ISSUE TITLE
Create Github Actions

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension#23]
### Background on the problem the feature will solve/improved user experience
Add GitHub Actions to lint new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch. 

GitHub Actions uses YAML syntax to define the events, jobs, and steps. These YAML files are stored in your code repository, in a directory called .github/workflows.

The action will 
- [ ] lint JS files, we haven't chosen a linter so let's discuss options in the comments
- [ ] lint markdown files in the repo

### Tasks
- [ ] Add linter (discuss in comments with @upkarlidder @josiemundi @demilolu) in `.github/workflows` folder. Prettier is a popular linter for both JS and MD files. See example in this [Call for Code project](https://github.com/Pyrrha-Platform/Pyrrha-Website/blob/main/.github/workflows/linter.yml).
- [ ] Ensure steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions)
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/TakeTwo-Marker-ChromeExtension/actions) to see if it worked.

### Acceptance Criteria 
- GitHub action runs for every new code commit and PR.

FYI @upkarlidder

**Comment by demilolu** [comment]
@KComrade53 i know Hacktoberfest is over, but was wondering if you were still interested in this issue :)
